-- Creates the database hbtn_0d_usa and the table states
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states(id INT UNIQUE AUTOGENERATED NOT NULL PRIMARY KEY, name VARCHAR(256)) IN hbtn_0d_usa;
